# Generated by Django 5.1.3 on 2025-03-21 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postImage', models.FileField(upload_to='posts/')),
                ('category', models.CharField(choices=[('landing', 'landing page'), ('e-commerce', 'e-commerce'), ('mobile', 'mobile app'), ('logo design', 'logo design'), ('icons', 'icons'), ('other', 'Other')], default='other', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
